### PR TITLE
Git submodules

### PR DESCRIPTION
**Pull request by pparaxan**
There's no point for them if you can just add them via cargo.

### CODE REVIEW

**Comment by a-catgirl-dev** [comment]
No.

**Comment by a-catgirl-dev** [comment]
you know the reason. clone with `git clone ... --recursive`

**Comment by a-catgirl-dev** [comment]
yikes 💀 

I'll test the pkgbuild during lunch. if you're right then I'll merge

**Comment by a-catgirl-dev** [comment]
nah xd clone and checkout tag in git go brrrrrrrrrrrr no free two commits for you cope meow

**Comment by pparaxan** [comment]
image

**Comment by a-catgirl-dev** [comment]
:3

**Comment by a-catgirl-dev** [comment]
ci

**Comment by pparaxan** [comment]
> ci

aaand i forgor about that

**Comment by a-catgirl-dev** [comment]
> > ci
> 
> aaand i forgor about that

:nyaboom:

**Pull request closed without merging**
